// CSS selectors for Bandcamp's native DOM elements.
export enum BC_ELEM_SELECTORS {
  pageBackground = "#pgBd",
  infoSection = "div#name-section",
  trackView = "div.trackView",
  fromAlbum = "span.fromAlbum",
  playerParent = "div.inline_player",
  inlinePlayerTable = "div.inline_player>table",
  audioPlayer = "audio",
  playPause = "div.playbutton",
  songPageCurrentTrackTitle = "h2.trackTitle",
  albumPageCurrentTrackTitle = "a.title_link",
  previousTrack = "div.prevbutton",
  nextTrack = "div.nextbutton",
  trackList = "table#track_table",
  trackRow = "tr.track_row_view",
  trackTitle = "span.track-title",
  trackDuration = "span.time",
  coverArt = "div#tralbumArt img",
}
