// CSS selectors for Plume's own injected DOM elements.
export enum PLUME_ELEM_SELECTORS {
  bcElements = "div#plume-hidden-original",
  plumeContainer = "div#plume-root",

  headerContainer = "div#plume-header-container",
  headerLogo = "a#plume-header-logo",
  headerCurrent = "div#plume-header-current",
  headerTitlePretext = "span#plume-header-title-pretext",
  headerTitle = "span#plume-header-title",
  headerTrackLink = "a#plume-header-track-link",
  tracklistToggleBtn = "button#plume-tracklist-toggle-btn",
  tracklistDropdown = "div#plume-tracklist-dropdown",
  tracklistItem = "div.plume-tracklist-item",

  playbackManager = "div#plume-playback-manager",
  playbackControls = "div#plume-playback-controls",
  progressContainer = "div#plume-progress-container",
  progressSlider = "input#plume-progress-slider",
  timeDisplay = "div#plume-time-display",
  elapsedDisplay = "span#plume-elapsed-display",
  durationDisplay = "button#plume-duration-display",

  speedWrapper = "div#plume-speed-wrapper",
  speedBtn = "button#plume-speed-btn",
  speedPopover = "div.plume-speed-popover",
  speedSlider = "input.plume-speed-slider",
  speedLabel = "span.plume-speed-label",
  trackBwdBtn = "button#plume-track-bwd-btn",
  timeBwdBtn = "button#plume-time-bwd-btn",
  playPauseBtn = "button#plume-play-pause-btn",
  timeFwdBtn = "button#plume-time-fwd-btn",
  trackFwdBtn = "button#plume-track-fwd-btn",
  loopBtn = "button#plume-loop-btn",

  volumeContainer = "div#plume-volume-container",
  muteBtn = "button#plume-mute-btn",
  volumeSlider = "input#plume-volume-slider",
  volumeValue = "div#plume-volume-value",

  fullscreenBtn = "button#plume-fullscreen-btn",
  fullscreenBtnLabel = "span#plume-fullscreen-btn-label",
  fullscreenBtnContainer = "div#plume-fullscreen-btn-container",
  fullscreenOverlay = "div#plume-fullscreen-overlay",
  fullscreenBackground = "div#plume-fullscreen-background",
  fullscreenContent = "div#plume-fullscreen-content",
  fullscreenExitBtn = "button#plume-fullscreen-exit-btn",
  fullscreenPresentationContainer = "div#plume-fullscreen-presentation",
  fullscreenCoverArt = "img#plume-fullscreen-cover-art",
  fullscreenTitlingContainer = "div.plume-fullscreen-titling",
  fullscreenTitlingRelease = "h2#plume-fullscreen-titling__release",
  fullscreenTitlingArtist = "h3#plume-fullscreen-titling__artist",
  fullscreenClone = "div#plume-fullscreen-clone",
}
